### PR TITLE
Update README with client and server commands

### PR DESCRIPTION
**Pull request by agnosticdev**
Update README echo server sample commands. 
The IPv6 localhost address `::1` was added on the client and the `-host` argument was removed on the server because this is the default address by default.

### CODE REVIEW

**Comment by agnosticdev** [comment]
Relates to issue 11: https://github.com/facebookincubator/mvfst/issues/11

**Comment by udippant** [comment]
While you are at it, can you propagate the `FLAGS_host` to `EchoServer` (like we do for `EchoClient`) and bind to the passed in address (while keeping the default address to ::1) :)?

**Comment by agnosticdev** [comment]
I will start looking into that.  Upon completion that will require an update to the `README` file again so I will make an update to the client and server commands as well.

**Comment by agnosticdev** [comment]
@udippant This PR has been updated with `FLAGS_host` propagating to the `EchoServer`.

**Comment by udippant** [comment]
Thank you! We will review it internally and merge it back.

**Comment by agnosticdev** [comment]
Is there any action needed from me on this PR at this time?

**Comment by udippant** [comment]
@agnosticdev  I have merged it back. Thank you for contributing.

**Comment by agnosticdev** [comment]
Thank you @udippant !

**Pull request closed without merging**
