### PR TITLE
Move the fizz code into its own package

### PR DESCRIPTION
**Pull request by deadalnix**
This moves the fizz specific part of the handshake into its own folder and library.

There is a bit of smurf naming going on as a result, not sure it is worth fixing or not at this stage. Maybe this code should be a in namespace named quic::fizz .

This should be doable with the client as well as soon as the key cache situation is figured out.

### CODE REVIEW

**Comment by udippant** [comment]
I do like the idea of separating the namespace given all the refactor and decoupling of fizz specific dependency (by you). The downside, however, is that the change will likely be quite pervasive.

Let us know if you want to update this PR with that change.

**Comment by deadalnix** [comment]
@udippant if you guys are happy with the namespace thing, then let's do this. Not sure this is appropriate as part of this patch because, as you mention, this will be a shotgun diff so better not to bundle it with something else and keep it standalone.

**Comment by udippant** [comment]
Ok, I'll import this. Looking forward to the next one :)

**Comment by udippant** [comment]
I've landed this commit - https://github.com/facebookincubator/mvfst/commit/74f98d460468319616aab2a298cafc4b7e5899a8 
Not sure why it didn't auto close this PR or commit as you.
 (I did have to do quite a number of iterations on it to fix internal builds :)

**Pull request closed without merging**
