### PR TITLE
Add mvfst specific encryption level

### PR DESCRIPTION
**Pull request by deadalnix**
This ensure a lot of code do not depend on fizz anymore.

### CODE REVIEW

**Comment by deadalnix** [comment]
I ran the test suite and is was all green, but maybe something was stale. Let me check.

**Comment by yangchi** [comment]
That's strange. Maybe our test in open source is set up wrong somehow. When I pulled this diff in and build on my devserver i got build error in quic/client/handshake/test/ClientHandshakeTest.cpp.

**Comment by deadalnix** [comment]
I'm think more of a stale dependency.

**Comment by yangchi** [comment]
Did you make the change? I don't see ClientHandshakeTest.cpp in the file list. Let me know when you make it and i will pull again.

**Comment by deadalnix** [comment]
After investigation, it turns out this test is not build using cmake.

This is fixed in https://github.com/facebookincubator/mvfst/pull/27

**Comment by yangchi** [comment]
should land soon. thank you!

**Pull request closed without merging**
